# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://oneil512.github.io"
baseurl: ""

# Name of website

name: Clay O'Neil
title: Clay O'Neil

# Short description of your site
description: ML Engineer

theme: alembic-jekyll-theme

footer-links:
  email: oneil512@umn.edu
  github: oneil512
  linkedin: clay-o-neil-b09564b0

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

