# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

url: "https://clayoneil.com"
baseurl: "/"

# Name of website

name: Clay O'Neil
title: Clay O'Neil

# Short description of your site
description: ML Engineer
avatar: https://raw.githubusercontent.com/oneil512/oneil512.github.io/master/images/me.jpg

footer-links:
  email: oneil512@umn.edu
  github: oneil512
  linkedin: clay-o-neil-b09564b0

baseurl: ""

kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

